import { useEffect, useMemo, useState } from "react";
import { api, type SearchResult } from "../api/client";
import { useWorkspace } from "../state/app-context";

const TYPE_OPTIONS = [
  { value: "", label: "Any type" },
  { value: "markdown", label: "Markdown" },
  { value: "table", label: "Table" },
  { value: "canvas", label: "Canvas" },
  { value: "board", label: "Board" },
];

function baseNoExt(path: string): string {
  const base = path.split("/").pop() ?? path;
  return base.replace(/\.[^.]+$/, "");
}

export function SearchPane({
  initialTag,
  initialQuery,
}: {
  initialTag?: string;
  initialQuery?: string;
}) {
  const { dispatch } = useWorkspace();
  const [query, setQuery] = useState("");
  const [tag, setTag] = useState(initialTag ?? "");
  const [type, setType] = useState("");
  const [folder, setFolder] = useState("");
  const [results, setResults] = useState<SearchResult[]>([]);
  const [active, setActive] = useState(0);

  useEffect(() => {
    if (initialTag !== undefined) {
      setTag(initialTag);
    }
  }, [initialTag]);

  useEffect(() => {
    if (initialQuery !== undefined) {
      setQuery(initialQuery);
    }
  }, [initialQuery]);

  const filters = useMemo(
    () => ({
      ...(tag ? { tag } : {}),
      ...(type ? { type } : {}),
      ...(folder ? { path: folder } : {}),
    }),
    [tag, type, folder],
  );

  useEffect(() => {
    const hasFilters = Boolean(tag || type || folder);
    if (query.trim().length === 0 && !hasFilters) {
      setResults([]);
      return;
    }
    let cancelled = false;
    const handle = setTimeout(() => {
      api
        .search(query.trim(), filters)
        .then((response) => {
          if (!cancelled) {
            setResults(response.results);
            setActive(0);
          }
        })
        .catch(() => {
          if (!cancelled) {
            setResults([]);
          }
        });
    }, 180);
    return () => {
      cancelled = true;
      clearTimeout(handle);
    };
  }, [query, filters, tag, type, folder]);

  const open = (result: SearchResult) =>
    dispatch({ type: "openFile", path: result.path, title: result.title || baseNoExt(result.path) });

  return (
    <div className="search-pane">
      <input
        className="search-input"
        data-testid="search-input"
        placeholder="Search notes…"
        value={query}
        onChange={(event) => setQuery(event.target.value)}
        onKeyDown={(event) => {
          if (event.key === "ArrowDown") {
            event.preventDefault();
            setActive((index) => Math.min(index + 1, results.length - 1));
          } else if (event.key === "ArrowUp") {
            event.preventDefault();
            setActive((index) => Math.max(index - 1, 0));
          } else if (event.key === "Enter" && results[active]) {
            open(results[active]);
          }
        }}
      />

      <div className="search-filters">
        <select
          className="search-filter"
          aria-label="Filter by type"
          value={type}
          onChange={(event) => setType(event.target.value)}
        >
          {TYPE_OPTIONS.map((option) => (
            <option key={option.value} value={option.value}>
              {option.label}
            </option>
          ))}
        </select>
        <input
          className="search-filter"
          aria-label="Filter by tag"
          placeholder="#tag"
          value={tag}
          onChange={(event) => setTag(event.target.value.replace(/^#/, ""))}
        />
        <input
          className="search-filter"
          aria-label="Filter by folder"
          placeholder="folder/"
          value={folder}
          onChange={(event) => setFolder(event.target.value.replace(/\/$/, ""))}
        />
      </div>

      {(query.trim().length > 0 || tag || type || folder) && results.length === 0 && (
        <div className="panel-empty">No results.</div>
      )}
      <ul className="search-results">
        {results.map((result, index) => (
          <li key={result.path}>
            <button
              className={`search-result ${index === active ? "search-result--active" : ""}`}
              onMouseEnter={() => setActive(index)}
              onClick={() => open(result)}
            >
              <span className="search-result-title">{result.title || baseNoExt(result.path)}</span>
              <span className="search-result-path">{result.path}</span>
              <span
                className="search-result-snippet"
                // Snippet HTML is generated by our own FTS index (only <mark> tags).
                dangerouslySetInnerHTML={{ __html: result.snippet }}
              />
            </button>
          </li>
        ))}
      </ul>
    </div>
  );
}
