import { defineConfig } from "tsdown";

/**
 * Bundles the Fastify server into a single CJS file for production Electron.
 * Runs from the apps/desktop/ directory, so server path is ../server/src/main.ts.
 * better-sqlite3 stays external — its native .node binary is copied by electron-builder.
 */
export default defineConfig({
  entry: ["../server/src/main.ts"],
  format: ["cjs"],
  outDir: "dist-server",
  sourcemap: true,
  platform: "node",
  target: "node20",
  outputOptions: {
    entryFileNames: "[name].js",
  },
  // Polyfill import.meta.url for CJS bundle (used in config.ts for __dirname equivalent)
  shims: true,
  banner: {
    js: "// Notes server bundle — generated by tsup",
  },
  deps: {
    neverBundle: ["better-sqlite3", "electron"],
    alwaysBundle: [/^@notes\//],
  },
  clean: false,
  dts: false,
});
